### ISSUE TITLE
[Usage] ImportError: cannot import name 'ShardedDDPOption' from 'transformers.trainer'

### ISSUE THREAD

**Issue by caopulan** [haotian-liu/LLaVA#1042]
### Describe the issue

transformers no longer has SharedDDPOption after v4.35.0

**Comment by attnmamba** [comment]
Same issue, looking for fix.
Following the pip install instructions in README, I have `transformers==4.36.2` installed, which is the version pinned by `pyproject.toml`

**Comment by haotian-liu** [comment]
Hi @caopulan @attnmamba

Sorry for the confusion. It should now be fixed in the main branch. Please let me know if it works for you, thanks.

**Comment by attnmamba** [comment]
@haotian-liu Thank you! The new commit solved the above issue, but there are warning message is constantly being printed out during finetuning:

First warning (printed once):

> /home/attnmamba/anaconda3/envs/llava/lib/python3.10/site-packages/torch/utils/checkpoint.py:31: UserWarning: None of the inputs have requires_grad=True. Gradients will be None


Repeated warnings (continuously printed):

> WARNING: tokenization mismatch: 1 vs. 57. (ignored)


My installed packages are

```
flash-attn                2.5.2
peft                      0.4.0
tokenizers                0.15.0
torch                     2.0.1
torchvision               0.15.2
transformers              4.36.2
```

Appears to be a previous issue you have addressed before https://github.com/haotian-liu/LLaVA/issues/661#issuecomment-1779692868

I tried `pip install "tokenizers>=0.12.1,<0.14"` and this isntalled `0.13.3`, but this gives another error when restarting the finetuning

```
Traceback (most recent call last):
  File "/home/attnmamba/llava/train/train_mem.py", line 9, in <module>
    from llava.train.llama_flash_attn_monkey_patch import replace_llama_attn_with_flash_attn
  File "/home/attnmamba/llava/__init__.py", line 1, in <module>
    from .model import LlavaLlamaForCausalLM
ImportError: cannot import name 'LlavaLlamaForCausalLM' from 'llava.model' (/home/attnmamba/llava/model/__init__.py)
```

**Comment by haotian-liu** [comment]
@attnmamba 

Would you mind sharing your command? I cannot reproduce the issue on my side. Thanks.

**Comment by attnmamba** [comment]
@haotian-liu Of course, here is my bash script

```bash
#!/bin/bash

deepspeed llava/train/train_mem.py \
    --lora_enable True --lora_r 128 --lora_alpha 256 --mm_projector_lr 2e-5 \
    --bits 4 \
    --deepspeed ./scripts/zero2.json \
    --model_name_or_path liuhaotian/llava-v1.5-13b \
    --version v1 \
    --data_path ./playground/data/my_instruct_82k.json \
    --image_folder ./playground/data/my_images \
    --vision_tower openai/clip-vit-large-patch14-336 \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir ./checkpoints/llava-v1.5-13b-task-lora \
    --num_train_epochs 1 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 2e-4 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb
```

Please let me know if theres more info I can provide

**Comment by attnmamba** [comment]
@haotian-liu Sorry false alarm, had some bad training examples in my dataset. No more warnings once those were removed.

Thank you very much for your help!

**Comment by will-wiki** [comment]
same error，transformers==4.36.2

**Comment by haotian-liu** [comment]
Nice, closing this issue :)

**Comment by ChenRan2000** [comment]
> ### Describe the issue
> transformers no longer has SharedDDPOption after v4

> ### Describe the issue
> transformers no longer has SharedDDPOption after v4.35.0

How to fix it, please tell me 0.0

**Comment by Liu0329** [comment]
> > ### Describe the issue
> > transformers no longer has SharedDDPOption after v4
> 
> > ### Describe the issue
> > transformers no longer has SharedDDPOption after v4.35.0
> 
> How to fix it, please tell me 0.0

Just disable import ShardedDDPOption, which is not used.

**Comment by nishitanand** [comment]
Still Facing this issue. Details - 

I am getting the following error, but this error should not be there -
cannot import name 'ShardedDDPOption' from 'transformers.trainer'

I have the following versions installed -
tokenizers-0.19.1
transformers-4.43.4
huggingface-hub-0.24.6

I have upgraded Vicuna -7v-v1.5 to llama 3.1 8B in this github repo - https://github.com/baaivision/EVE

This works with the vicuna-7b-v1.5, but not with llama3.1 8B. It should work as there isn't much change. I earlier got rope error, but solved it by upgrading transformers as guided in this issue -
https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct/discussions/15

I run bash eve7b_prealign.sh 0 localhost. This worked and I was able to train vicuna-7b-v1.5, but facing error with llama 3.1 8b
