### ISSUE TITLE
[Usage] Getting an ImportError:cannot import name 'LlavaLlamaForCasualLM' 

### ISSUE THREAD

**Issue by slaser79** [haotian-liu/LLaVA#1060]
### Describe the issue

Issue:

I am getting an import error as below. This was after pulling the lastest master version and running ```pip install -e  .```
This used to work in the past when running llava-v1.5.

Command:
```
 python -m llava.serve.model_worker --host 0.0.0.0 --controller http://localhost:10000 --port 40000 --worker http://localhost:40000 --model-path liuhaotian/llava-v1.6-mistral-7b --load-4bit
```

Log: 
```
[2024-02-03 13:13:22,402] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/home/slaser79/anaconda3/envs/llava/lib/python3.10/site-packages/pydantic/_internal/_config.py:322: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
* 'validate_all' has been renamed to 'validate_default'
  warnings.warn(message, UserWarning)
/home/slaser79/anaconda3/envs/llava/lib/python3.10/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_persistence_threshold" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
Traceback (most recent call last):
  File "/home/slaser79/anaconda3/envs/llava/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/slaser79/anaconda3/envs/llava/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/slaser79/lab/LLaVA/llava/__init__.py", line 1, in <module>
    from .model import LlavaLlamaForCausalLM
ImportError: cannot import name 'LlavaLlamaForCausalLM' from 'llava.model' (/home/slaser79/lab/LLaVA/llava/model/__init__.py)


```

**Comment by InconsolableCellist** [comment]
What version of Python do you have in your environment? I got this error when I used something higher than 3.10

**Comment by slaser79** [comment]
It was python 3.10..I recloned the project and reinstalled the dependencies and now it works! So I think it is related to upgrade instructions.
